#!/bin/bash
# Copyright 2018 - 2023 Ayogo Health Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

INKSCAPE='inkscape'

if [[ "$OSTYPE" == "darwin"* ]]; then
    INKSCAPE='/Applications/Inkscape.app/Contents/MacOS/Inkscape'

    if [ ! -f "$INKSCAPE" ]; then
        INKSCAPE='/Applications/Inkscape.app/Contents/MacOS/inkscape'
    fi
fi

$INKSCAPE --version | grep -Eq '^Inkscape 0\.'
VERSION=$?

IMAGICK='magick'
if ! command -v $IMAGICK &> /dev/null
then
    IMAGICK='convert'
fi


VERBOSE=false
WITH_ANDROID=true
WITH_ANDROID_VECTOR=true
WITH_ANDROID_LEGACY=false
WITH_IOS=true
WITH_IOS_LEGACY=false
WITH_WEB=false

# Icon sizes for iOS
SIZES=(
    AppIcon:57
    AppIcon@2x:114
    AppIcon-20x20@1x:20:white
    AppIcon-20x20@2x:40:white
    AppIcon-20x20@3x:60:white
    AppIcon-40x40@1x:40:white
    AppIcon-40x40@2x:80:white
    AppIcon-40x40@3x:120:white
    AppIcon-50x50@1x:50:white
    AppIcon-50x50@2x:100:white
    AppIcon-60x60@1x:60
    AppIcon-60x60@2x:120
    AppIcon-60x60@3x:180
    AppIcon-72x72@1x:72
    AppIcon-72x72@2x:144
    AppIcon-76x76@1x:76
    AppIcon-76x76@2x:152
    AppIcon-83.5x83.5@2x:167
    AppIcon-1024x1024@1x:1024
    AppIcon-29x29@1x:29:white
    AppIcon-29x29@2x:58:white
    AppIcon-29x29@3x:87:white
    AppIcon-24x24@2x:48:white
    AppIcon-27.5x27.5@2x:55:white
    AppIcon-44x44@2x:88:white
    AppIcon-86x86@2x:172:white
    AppIcon-98x98@2x:196:white
)

# Icon sizes for Android
DENSITIES=(
    ldpi:36
    mdpi:48
    hdpi:72
    xhdpi:96
    xxhdpi:144
    xxxhdpi:192
)

# Icon sizes for web favicons
FAVICONS=(
    icon-16:16:transparent
    icon-32:32:transparent
    icon-48:48:transparent
    icon-192:192
    icon-512:512
    apple-touch-icon:180
)

BACKGROUND="transparent"
FORCE_BACKGROUND=false

USAGE="Usage: $0 [-d] [-b COLOR] [--force-bg] INPUTFILE [OUTPUTDIR]
\n
\nThis tool generates app icons for iOS and Android apps from the SVG file given in INPUTFILE. It is expected that the input file is an SVG with a square canvas size and a transparent background. A solid background colour can be added to the output via the --background (-b) option.
\nIf OUTPUTDIR is not specified, it defaults to a folder named 'out' in the current directory.
\n
\nNOTE: This script requires the following tools to be installed and available:
\n\tInkscape\t-- https://inkscape.org/
\n\tpngquant\t-- https://pngquant.org/
\n\tzopflipng\t-- https://github.com/google/zopfli
\n\tImageMagick\t-- https://imagemagick.org/
\n\tlibxml2\t\t-- https://gitlab.gnome.org/GNOME/libxml2
\n\tnpm\t\t-- https://npmjs.org/
\n\tjava\t\t-- https://openjdk.org/
\n
\nOptions:
\n\t-h
\n\t--help\t\tPrint this message.
\n
\n\t-d
\n\t--debug
\n\t-v
\n\t--verbose\tTurn on debugging output.
\n
\n\t-b
\n\t--background\tSet the background colour.
\n
\n\t--force-bg\tAlways use the specified background colour, not white.
\n
\n\t--ios\t\tGenerate iOS icons (default).
\n\t--no-ios\tDo not generate iOS icons.
\n\t--ios-old\tGenerate all icon sizes for older Xcode versions.
\n
\n\t--android\tGenerate Android icons (default).
\n\t--no-android\tDo not generate Android icons.
\n\t--no-vector\tDo not generate Android adaptive vector icons.
\n\t--android-old\tGenerate mipmap icons for older Android versions.
\n
\n\t--web\t\tGenerate web favicons.
\n\t--no-web\tDo not generate web favicons (default)."

while getopts ":dhb:-:" opt; do
    case $opt in
        b)
            BACKGROUND=${OPTARG}
            ;;
        v)
            set -x
            VERBOSE=true
            ;;
        d)
            set -x
            VERBOSE=true
            ;;
        h)
            echo -e $USAGE
            exit
            ;;
        -)
            case "${OPTARG}" in
                verbose)
                    set -x
                    VERBOSE=true
                    ;;
                debug)
                    set -x
                    VERBOSE=true
                    ;;
                background=*)
                    BACKGROUND=${OPTARG#*=}
                    ;;
                force-bg)
                    FORCE_BACKGROUND=true
                    ;;
                no-ios)
                    WITH_IOS=false
                    WITH_IOS_LEGACY=false
                    ;;
                no-android)
                    WITH_ANDROID=false
                    WITH_ANDROID_LEGACY=false
                    WITH_ANDROID_VECTOR=false
                    ;;
                no-vector)
                    WITH_ANDROID_VECTOR=false
                    ;;
                no-web)
                    WITH_WEB=false
                    ;;
                ios)
                    WITH_IOS=true
                    ;;
                ios-old)
                    WITH_IOS_LEGACY=true
                    ;;
                android)
                    WITH_ANDROID=true
                    ;;
                android-old)
                    WITH_ANDROID_LEGACY=true
                    ;;
                web)
                    WITH_WEB=true
                    ;;
                help)
                    echo -e $USAGE
                    exit
                    ;;
            esac
            ;;
    esac
done

shift "$((OPTIND-1))"

SAVEIFS=$IFS

if [ -z "$1" ]; then
    echo -e $USAGE
    exit
fi

checktool() {
    if ! command -v $@ &> /dev/null
    then
        echo "$@ not be found" 1>&2;
        echo -e $USAGE
        exit
    fi
}

checktool pngquant
checktool zopflipng
checktool $INKSCAPE
checktool $IMAGICK
checktool xmllint
checktool npx


if [ "$VERBOSE" = true ]; then
    echo "Android: $WITH_ANDROID ( vector: $WITH_ANDROID_VECTOR , legacy: $WITH_ANDROID_LEGACY ); iOS: $WITH_IOS ( legacy: $WITH_IOS_LEGACY ); web: $WITH_WEB"
fi

OUTDIR=${2:-out}

# Generate our iOS icons
if [ "$WITH_IOS" = true ]; then
    mkdir -p "$OUTDIR/ios"
    mkdir -p "$OUTDIR/tmp"

    if [ "$WITH_IOS_LEGACY" = true ]; then
        for size in "${SIZES[@]}"; do
            IFS=':' read -ra ICON <<< "$size";

            BGCOL="${ICON[2]:-$BACKGROUND}"
            if [ "$FORCE_BACKGROUND" = true ]; then
                BGCOL=$BACKGROUND
            fi

            OPACITY=$([[ "$BGCOL" == "transparent" ]] && echo "0.0" || echo "1.0")

            if [ $VERSION -eq 0 ]; then
                $INKSCAPE -b "$BGCOL" -h "${ICON[1]}" -w "${ICON[1]}" -e "$OUTDIR/tmp/${ICON[0]}.png" "$1"
            else
                $INKSCAPE -b "$BGCOL" -y $OPACITY -h "${ICON[1]}" -w "${ICON[1]}" -o "$OUTDIR/tmp/${ICON[0]}.png" "$1"
            fi

            pngquant --strip --speed 1 "$OUTDIR/tmp/${ICON[0]}.png"
            rm "$OUTDIR/tmp/${ICON[0]}.png"
            zopflipng -m "$OUTDIR/tmp/${ICON[0]}-fs8.png" "$OUTDIR/ios/${ICON[0]}.png"
            rm "$OUTDIR/tmp/${ICON[0]}-fs8.png"
        done
    else
        # We can generate just a single 1024x1024 icon
        BGCOL="${BACKGROUND:-white}"
        if [ $VERSION -eq 0 ]; then
            $INKSCAPE -b "$BGCOL" -h "1024" -w "1024" -e "$OUTDIR/tmp/icon.png" "$1"
        else
            $INKSCAPE -b "$BGCOL" -y "1.0" -h "1024" -w "1024" -o "$OUTDIR/tmp/icon.png" "$1"
        fi

        pngquant --strip --speed 1 "$OUTDIR/tmp/icon.png"
        rm "$OUTDIR/tmp/icon.png"
        zopflipng -m "$OUTDIR/tmp/icon-fs8.png" "$OUTDIR/ios/icon.png"
        rm "$OUTDIR/tmp/icon-fs8.png"
    fi

    rmdir "$OUTDIR/tmp"
fi


# Generate our Android icons
if [ "$WITH_ANDROID" = true ]; then
    mkdir -p "$OUTDIR/android"
    mkdir -p "$OUTDIR/tmp"

    if [ "$WITH_ANDROID_LEGACY" = true ]; then
        TEMPLATE_HEAD='<?xml version="1.0" encoding="utf-8"?>\n<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 192 192">\n<defs>\n  <clipPath id="androidMask">\n    <rect x="20" y="20" rx="12" ry="12" height="152" width="152"></rect>\n  </clipPath>\n</defs>\n<rect x="0" y="0" height="192" width="192" fill="'"${BACKGROUND}"'" clip-path="url(#androidMask)"/>'
        TEMPLATE_TAIL='<use xlink:href="#iconize-base" x="20" y="20" width="152" height="152" clip-path="url(#androidMask)"></use>\n</svg>'

        CIRC_TEMPLATE_HEAD='<?xml version="1.0" encoding="utf-8"?>\n<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 192 192">\n<defs>\n  <clipPath id="androidMask">\n    <rect x="8" y="8" rx="50%" ry="50%" height="176" width="176"></rect>\n  </clipPath>\n</defs>\n<rect x="0" y="0" height="192" width="192" fill="'"${BACKGROUND}"'" clip-path="url(#androidMask)"/>'
        CIRC_TEMPLATE_TAIL='<use xlink:href="#iconize-base" x="8" y="8" width="176" height="176" clip-path="url(#androidMask)"></use>\n</svg>'

        echo -e $TEMPLATE_HEAD > "$OUTDIR/tmp/android.svg"
        sed -e 's/<\?xml.*\?>//' -e 's/<svg/<symbol id="iconize-base"/' -e 's/ *xmlns="[^\"]*"//' -e 's/<\/svg/<\/symbol/' "$1" >> "$OUTDIR/tmp/android.svg"
        echo -e $TEMPLATE_TAIL >> "$OUTDIR/tmp/android.svg"

        echo -e $CIRC_TEMPLATE_HEAD > "$OUTDIR/tmp/android-round.svg"
        sed -e 's/<\?xml.*\?>//' -e 's/<svg/<symbol id="iconize-base"/' -e 's/ *xmlns="[^\"]*"//' -e 's/<\/svg/<\/symbol/' "$1" >> "$OUTDIR/tmp/android-round.svg"
        echo -e $CIRC_TEMPLATE_TAIL >> "$OUTDIR/tmp/android-round.svg"

        for size in "${DENSITIES[@]}"; do
            IFS=':' read -ra ICON <<< "$size";

            if [ $VERSION -eq 0 ]; then
                $INKSCAPE -h "${ICON[1]}" -w "${ICON[1]}" -e "$OUTDIR/tmp/${ICON[0]}.png" "$OUTDIR/tmp/android.svg"
                $INKSCAPE -h "${ICON[1]}" -w "${ICON[1]}" -e "$OUTDIR/tmp/${ICON[0]}-round.png" "$OUTDIR/tmp/android-round.svg"
            else
                $INKSCAPE -h "${ICON[1]}" -w "${ICON[1]}" -o "$OUTDIR/tmp/${ICON[0]}.png" "$OUTDIR/tmp/android.svg"
                $INKSCAPE -h "${ICON[1]}" -w "${ICON[1]}" -o "$OUTDIR/tmp/${ICON[0]}-round.png" "$OUTDIR/tmp/android-round.svg"
            fi

            mkdir -p "$OUTDIR/android/mipmap-${ICON[0]}"

            pngquant --strip --speed 1 "$OUTDIR/tmp/${ICON[0]}.png"
            rm "$OUTDIR/tmp/${ICON[0]}.png"
            zopflipng -m "$OUTDIR/tmp/${ICON[0]}-fs8.png" "$OUTDIR/android/mipmap-${ICON[0]}/ic_launcher.png"
            rm "$OUTDIR/tmp/${ICON[0]}-fs8.png"

            pngquant --strip --speed 1 "$OUTDIR/tmp/${ICON[0]}-round.png"
            rm "$OUTDIR/tmp/${ICON[0]}-round.png"
            zopflipng -m "$OUTDIR/tmp/${ICON[0]}-round-fs8.png" "$OUTDIR/android/mipmap-${ICON[0]}/ic_launcher_round.png"
            rm "$OUTDIR/tmp/${ICON[0]}-round-fs8.png"
        done

        rm "$OUTDIR/tmp/android.svg"
        rm "$OUTDIR/tmp/android-round.svg"
    fi

    if [ "$WITH_ANDROID_VECTOR" = true ]; then
        # We need to convert the SVG into an Android VectorDrawable
        # Android Studio has a tool for this, which someone repackaged on npm. It requires Java.
        #
        # But first, we actually need to manipulate our SVG to add the right amount of padding...
        #
        # This is where it gets very hacky:
        # Our original viewBox needs to be scaled such that it fills 72dp centered in a 108dp frame.
        # We use xmllint to extract the viewBox values from the original SVG, then use awk to parse and recalculate the offsets and dimensions, and finally use sed to adjust a copy of the original SVG
        #
        # Believe it or not, I had this as a one-liner (it was terrible) but I have graciously split it up here for easier reading :P
        OLD_VIEWBOX=$(xmllint --xpath 'string(//@viewBox)' "$1")
        NEW_VIEWBOX=$(echo $OLD_VIEWBOX | awk -F' ' '{ print (int($1) - ((int($3) * 108/72 - int($3)) / 2)) " " (int($2) - ((int($4) * 108/72 - int($4)) / 2)) " " (int($3) * 108/72) " " (int($4) * 108/72) }')
        sed -e "s/viewBox=\"$OLD_VIEWBOX\"/viewBox=\"$NEW_VIEWBOX\"/" "$1" > "$OUTDIR/tmp/ic_launcher_foreground.svg"

        mkdir -p "$OUTDIR/android/drawable-v24"
        npx -y vd-tool -c -in "$OUTDIR/tmp/ic_launcher_foreground.svg" -widthDp 108 -heightDp 108 -out "$OUTDIR/android/drawable-v24/"

        rm "$OUTDIR/tmp/ic_launcher_foreground.svg"
    fi

    # Store Icon: No transparency, no rounded corners
    BGCOL="${BACKGROUND:-white}"
    if [ $VERSION -eq 0 ]; then
        $INKSCAPE -b "$BGCOL" -h "512" -w "512" -e "$OUTDIR/tmp/ic_launcher-playstore.png" "$1"
    else
        $INKSCAPE -b "$BGCOL" -y "1.0" -h "512" -w "512" -o "$OUTDIR/tmp/ic_launcher-playstore.png" "$1"
    fi

    pngquant --strip --speed 1 "$OUTDIR/tmp/ic_launcher-playstore.png"
    rm "$OUTDIR/tmp/ic_launcher-playstore.png"
    zopflipng -m "$OUTDIR/tmp/ic_launcher-playstore-fs8.png" "$OUTDIR/android/ic_launcher-playstore.png"
    rm "$OUTDIR/tmp/ic_launcher-playstore-fs8.png"
    # End Store Icon

    rmdir "$OUTDIR/tmp"
fi


# Generate web favicons
if [ "$WITH_WEB" = true ]; then
    mkdir -p "$OUTDIR/web"
    mkdir -p "$OUTDIR/tmp"

    for size in "${FAVICONS[@]}"; do
        IFS=':' read -ra ICON <<< "$size";

        BGCOL="${ICON[2]:-$BACKGROUND}"
        if [ "$FORCE_BACKGROUND" = true ]; then
            BGCOL=$BACKGROUND
        fi

        OPACITY=$([[ "$BGCOL" == "transparent" ]] && echo "0.0" || echo "1.0")

        if [ $VERSION -eq 0 ]; then
            if [ "$BGCOL" == "transparent" ]; then
                $INKSCAPE -h "${ICON[1]}" -w "${ICON[1]}" -e "$OUTDIR/tmp/${ICON[0]}.png" "$1"
            else
                $INKSCAPE -b "$BGCOL" -h "${ICON[1]}" -w "${ICON[1]}" -e "$OUTDIR/tmp/${ICON[0]}.png" "$1"
            fi
        else
            $INKSCAPE -b "$BGCOL" -y $OPACITY -h "${ICON[1]}" -w "${ICON[1]}" -o "$OUTDIR/tmp/${ICON[0]}.png" "$1"
        fi

        pngquant --strip --speed 1 "$OUTDIR/tmp/${ICON[0]}.png"
        rm "$OUTDIR/tmp/${ICON[0]}.png"
        zopflipng -m "$OUTDIR/tmp/${ICON[0]}-fs8.png" "$OUTDIR/web/${ICON[0]}.png"
        rm "$OUTDIR/tmp/${ICON[0]}-fs8.png"
    done

    cp "$1" "$OUTDIR/web/favicon.svg"
    $IMAGICK "$OUTDIR/web/icon-16.png" "$OUTDIR/web/icon-32.png" "$OUTDIR/web/icon-48.png" -colors 256 "$OUTDIR/web/favicon.ico"
    rm "$OUTDIR/web/icon-16.png"
    rm "$OUTDIR/web/icon-32.png"
    rm "$OUTDIR/web/icon-48.png"

    rmdir "$OUTDIR/tmp"
fi

IFS=$SAVEIFS
