#!/bin/bash
# Copyright 2018 Ayogo Health Inc.

INKSCAPE='inkscape'

if [[ "$OSTYPE" == "darwin"* ]]; then
    INKSCAPE='/Applications/Inkscape.app/Contents/MacOS/Inkscape'

    if [ ! -f "$INKSCAPE" ]; then
        INKSCAPE='/Applications/Inkscape.app/Contents/MacOS/inkscape'
    fi
fi

$INKSCAPE --version | grep -Eq '^Inkscape 0\.'
VERSION=$?

BACKGROUND="transparent"
DENSITIES=(notification-mdpi:22:24 notification-hdpi:33:36 notification-xhdpi:44:48 notification-xxhdpi:66:72 notification-xxxhdpi:88:96)

SAVEIFS=$IFS
OUTDIR=${2:-out}

mkdir -p $OUTDIR/android
mkdir -p $OUTDIR/tmp

for size in "${DENSITIES[@]}"; do
    IFS=':' read -ra ICON <<< "$size";

    if [ $VERSION -eq 0 ]; then
        $INKSCAPE -h "${ICON[1]}" -w "${ICON[1]}" -e "$OUTDIR/tmp/${ICON[0]}-orig.png" "$1"
    else
        $INKSCAPE -h "${ICON[1]}" -w "${ICON[1]}" -o "$OUTDIR/tmp/${ICON[0]}-orig.png" "$1"
    fi

    convert "$OUTDIR/tmp/${ICON[0]}-orig.png" -background "$BACKGROUND" -gravity center -scale "${ICON[1]}x${ICON[1]}" -extent "${ICON[2]}x${ICON[2]}" "$OUTDIR/tmp/${ICON[0]}.png"
    rm "$OUTDIR/tmp/${ICON[0]}-orig.png"

    pngquant --strip --speed 1 "$OUTDIR/tmp/${ICON[0]}.png"
    rm "$OUTDIR/tmp/${ICON[0]}.png"
    zopflipng -m "$OUTDIR/tmp/${ICON[0]}-fs8.png" "$OUTDIR/android/${ICON[0]}.png"
    rm "$OUTDIR/tmp/${ICON[0]}-fs8.png"
done

rmdir $OUTDIR/tmp

IFS=$SAVEIFS
