#!/bin/bash
# Copyright 2018 - 2023 Ayogo Health Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

INKSCAPE='inkscape'

if [[ "$OSTYPE" == "darwin"* ]]; then
    INKSCAPE='/Applications/Inkscape.app/Contents/MacOS/Inkscape'

    if [ ! -f "$INKSCAPE" ]; then
        INKSCAPE='/Applications/Inkscape.app/Contents/MacOS/inkscape'
    fi
fi

$INKSCAPE --version | grep -Eq '^Inkscape 0\.'
VERSION=$?

BACKGROUND="transparent"
DENSITIES=(notification-mdpi:22:24 notification-hdpi:33:36 notification-xhdpi:44:48 notification-xxhdpi:66:72 notification-xxxhdpi:88:96)

SAVEIFS=$IFS
OUTDIR=${2:-out}

mkdir -p $OUTDIR/android
mkdir -p $OUTDIR/tmp

for size in "${DENSITIES[@]}"; do
    IFS=':' read -ra ICON <<< "$size";

    if [ $VERSION -eq 0 ]; then
        $INKSCAPE -h "${ICON[1]}" -w "${ICON[1]}" -e "$OUTDIR/tmp/${ICON[0]}-orig.png" "$1"
    else
        $INKSCAPE -h "${ICON[1]}" -w "${ICON[1]}" -o "$OUTDIR/tmp/${ICON[0]}-orig.png" "$1"
    fi

    convert "$OUTDIR/tmp/${ICON[0]}-orig.png" -background "$BACKGROUND" -gravity center -scale "${ICON[1]}x${ICON[1]}" -extent "${ICON[2]}x${ICON[2]}" "$OUTDIR/tmp/${ICON[0]}.png"
    rm "$OUTDIR/tmp/${ICON[0]}-orig.png"

    pngquant --strip --speed 1 "$OUTDIR/tmp/${ICON[0]}.png"
    rm "$OUTDIR/tmp/${ICON[0]}.png"
    zopflipng -m "$OUTDIR/tmp/${ICON[0]}-fs8.png" "$OUTDIR/android/${ICON[0]}.png"
    rm "$OUTDIR/tmp/${ICON[0]}-fs8.png"
done

rmdir $OUTDIR/tmp

IFS=$SAVEIFS
